/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch v3/v2 token set (2026-08-18 refresh)
        "inverse-primary": "#4edea3",
        "on-tertiary-container": "#711419",
        "on-secondary-container": "#fefcff",
        "surface-container": "#FFFFFF",
        "on-error-container": "#93000a",
        "primary-container": "#10b981",
        "tertiary-container": "#fc7c78",
        "on-background": "#161d19",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#842225",
        "on-secondary-fixed-variant": "#003ea8",
        tertiary: "#a43a3a",
        surface: "#F7F8FA",
        "surface-variant": "#dde4dd",
        "surface-bright": "#f4fbf4",
        "on-surface": "#161d19",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e3eae3",
        "tertiary-fixed": "#ffdad7",
        "outline-variant": "#bbcabf",
        "primary-fixed": "#6ffbbe",
        secondary: "#0051d5",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#410005",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3c4a42",
        primary: "#006c49",
        background: "#f4fbf4",
        "tertiary-fixed-dim": "#ffb3af",
        "surface-dim": "#d4dcd5",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#ebf3eb",
        "inverse-surface": "#2b322d",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#005236",
        outline: "#E2E8F0",
        "secondary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#00174b",
        "surface-container-low": "#eef6ee",
        "primary-fixed-dim": "#4edea3",
        "on-error": "#ffffff",
        "surface-tint": "#006c49",
        "on-primary-container": "#00422b",
        "surface-container-highest": "#dde4dd",
        "secondary-container": "#316bf3",
        "on-primary-fixed": "#002113",
        // Additive accents kept from the original build — not in the Stitch
        // export, but reused across CTAs/icons and don't conflict with the
        // token names above.
        "brand-emerald": "#10B981",
        "brand-emerald-dark": "#059669",
        "tech-blue": "#3B82F6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "column-gap": "24px",
        "margin-mobile": "16px",
        gutter: "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        annotation: ["JetBrains Mono"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        annotation: [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
    },
  },
}
