/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#000000",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#45464d",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        primary: "#000000",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3a485c",
        "primary-container": "#131b2e",
        "secondary-container": "#d5e3fd",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d5e3fd",
        "status-success": "#D1FAE5",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3f465c",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#002113",
        "primary-fixed-dim": "#bec6e0",
        "surface-container": "#eceef0",
        "on-secondary-container": "#57657b",
        "inverse-surface": "#2d3133",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary": "#ffffff",
        background: "#f7f9fb",
        "border-gray": "#E2E8F0",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0",
        "on-background": "#191c1e",
        "on-tertiary-container": "#009668",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eff1f3",
        "on-error": "#ffffff",
        "tech-blue": "#3B82F6",
        "on-tertiary-fixed-variant": "#005236",
        surface: "#f7f9fb",
        outline: "#76777d",
        "text-muted": "#64748B",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        secondary: "#515f74",
        "on-secondary-fixed": "#0d1c2f",
        "secondary-fixed-dim": "#b9c7e0",
        error: "#ba1a1a",
        "brand-emerald": "#10B981",
        "brand-emerald-dark": "#059669",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1120px",
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "section-gap": "80px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-caps": [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
}
